apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bike-lgbm-scale
  namespace: kserve-inference
spec:
  predictor:
    serviceAccountName: kserve-sa
    ### START CONF HERE
    minReplicas: 2
    maxReplicas: 8
    scaleTarget: 5
    scaleMetric: rps
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlflow/8/0003ece124ee4cdf861e0ed8dd574ab2/artifacts/lgbm-bike"
    ### END CONF HERE